---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: output-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumerapplogs-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: consumer
  replicas: 3
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 605125156525.dkr.ecr.ap-southeast-1.amazonaws.com/load-consumer:0.0.18
        imagePullPolicy: IfNotPresent
        env:
        - name: NUM_JOBS
          value: "10"
        - name: NUM_WORKERS
          value: "10"
        - name: KAFKA_BROKER1_ADDRESS
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER2_ADDRESS
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_BROKER3_ADDRESS
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: LOCAL_LOGFILE_PATH
          value: "/applogs"
        - name: MESSAGE_TOPIC
          value: "messages"
        - name: DEADLETTER_TOPIC
          value: "deadLetter"
        - name: METRICS_TOPIC
          value: "metrics"      
        - name: TARGET_API_URL
          value: "http://sink-service.ragnarok.svc.cluster.local/orders"
        - name: PORT_NUMBER
          value: "80"
        ports:
          - name: tcp-80
            containerPort: 80
        volumeMounts:
          - name: applogs
            mountPath: /applogs
          - name: output
            mountPath: /output-api
      volumes:
        - name: applogs
          persistentVolumeClaim:
            claimName: consumerapplogs-claim
        - name: output
          persistentVolumeClaim:
            claimName: output-claim
      imagePullSecrets:
        - name: ragnarok

---

kind: Service
apiVersion: v1
metadata:
  name: consumer-service
  namespace: ragnarok
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - name: tcp-80
      port: 80
      nodePort: 30081
      protocol: TCP
