apiVersion: v1
kind: Pod
metadata:
  name: redisclient
  namespace: default
spec:
  containers:
  - name: redis-client
    image:  airdock/redis-client
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
