apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: streamer-modify-pods-to-sa
  namespace: pulsar
subjects:
  - kind: ServiceAccount
    name: streamer-internal-kubectl
    namespace: ragnarok
roleRef:
  kind: Role
  name: streamer-modify-pods
  apiGroup: rbac.authorization.k8s.io
