apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: pulsar
rules:
  - apiGroups: ["","apps"]
    resources:
      - pods
      - statefulsets
      - deployments
    verbs:
      - get
      - list
      - delete
      - scale
      - restart
