{
 "title": "Transaction Matching System Load Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Order Cancellation Volumes",
   "type": "timeseries",
   "description": "Volume of Cancelled orders and Failed Order Cancellations",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "load_cancel_successul_requests_total{group=\"load-consumers\"}"
    },
    {
     "expr": "load_cancel_failed_requests_total{group=\"load-consumers\"}"
    }
   ]
  },
  {
   "title": "Producer Pool Concurrency Metrics",
   "type": "timeseries",
   "description": "Concurrent Workers and Jobs for the producer pool",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "load_producer_concurrent_workers{}"
    },
    {
     "expr": "load_producer_concurrent_jobs{}"
    }
   ]
  },
  {
   "title": "Input File Generator Metrics (volumes)",
   "type": "timeseries",
   "description": "Input Request file generation and error metrics for the input file loader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "load_files_generated_total{}" },
    { "expr": "load_files_errors_total{}" }
   ]
  },
  {
   "title": "Worker Pool Concurrency Metrics",
   "type": "timeseries",
   "description": "Concurrent Worker and Job count per Worker pool instance of Golang",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "load_consumer_concurrent_jobs{}"
    },
    {
     "expr": "load_consumer_concurrent_workers{}"
    }
   ]
  },
  {
   "title": "Work Allocation Table Buildup",
   "type": "timeseries",
   "description": "Volume of Orders assigned to Workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "orders_allocated_workers_total{group=\"loader-service\"}"
    }
   ]
  },
  {
   "title": "Target System Load Metrics (Rate)",
   "type": "timeseries",
   "description": "Load Metrics of the System under Load Testing",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(loadsink_failed_requests_total[1m])",
     "legendFormat": "loadsink_failed_requests per minute"
    },
    {
     "expr": "rate(loadsink_successul_requests_total[1m])",
     "legendFormat": "oadsink_successul_requests per minute"
    }
   ]
  },
  {
   "title": "Orders Allocated to Workers (Rate of Allocation Table Build)",
   "type": "timeseries",
   "description": "Rate at which new orders allocation table is built up",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(orders_allocated_workers_total{group=\"loader-service\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Input File Generator Metrics (rates)",
   "type": "timeseries",
   "description": "Input file generation rate",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(load_files_generated_total[1m])",
     "legendFormat": "input files generated per minute"
    },
    {
     "expr": "rate(load_files_errors_total[1m])"
    }
   ]
  },
  {
   "title": "Source Order Data Loader",
   "type": "timeseries",
   "description": "Performance of Order Source Data Loader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(load_orders_ingested_total[1m])"
    },
    {
     "expr": "rate(load_orders_ingesterrors_total[1m])"
    }
   ]
  },
  {
   "title": "Redis Cluster Performance ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "redis_blocked_clients{instance=\"ragnarok-redis-metrics.ragnarok.svc.cluster.local:9121\"}"
    },
    {
     "expr": "redis_cluster_connections{instance=\"ragnarok-redis-metrics.ragnarok.svc.cluster.local:9121\"}"
    },
    {
     "expr": "redis_rejected_connections_total{}"
    },
    { "expr": "redis_uptime_in_seconds{}" }
   ]
  },
  {
   "title": "Producer Pool Load GenerationMetrics",
   "type": "timeseries",
   "description": "Metrics indicating the Load Generation performance of the producer pool",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(load_producer_failed_requests_total[1m])",
     "legendFormat": "failed requests per minute"
    },
    {
     "expr": "rate(load_producer_input_requests_total[1m])",
     "legendFormat": "input requests per minute"
    },
    {
     "expr": "rate(load_producer_submit_requests_total[1m])",
     "legendFormat": "submitted requests per minute"
    }
   ]
  },
  {
   "title": "Consumer Pool Load Generation Metrics",
   "type": "timeseries",
   "description": "Requests consumed from the load message queue vs. requests failed to post to the target api",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(load_consumer_consumed_requests_total[1m])",
     "legendFormat": "consumed requests per minute"
    },
    {
     "expr": "rate(load_consumer_failed_requests_total[1m])",
     "legendFormat": "request consume failures per minute"
    },
    {
     "expr": "rate(load_consumer_successul_requests_total[1m])",
     "legendFormat": "successfully posted requests per minute"
    }
   ]
  },
  {
   "title": "Target Application Load Metrics (Volume)",
   "type": "timeseries",
   "description": "Inbound Request Load Statistics for Target Application",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "loadsink_failed_requests_total{}"
    },
    {
     "expr": "loadsink_successul_requests_total{}"
    }
   ]
  }
 ]
}