apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: loader-modify-pods-to-sa
  namespace: ragnarok
subjects:
  - kind: ServiceAccount
    name: loader-internal-kubectl
roleRef:
  kind: Role
  name: loader-modify-pods
  apiGroup: rbac.authorization.k8s.io
