apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: loader-modify-pods
  namespace: ragnarok
rules:
  - apiGroups: ["","apps"]
    resources:
      - pods
      - deployments
      - statefulsets
      - "statefulsets/scale"
      - "deployments/scale"
    verbs:
      - get
      - list
      - delete
      - scale
      - create
      - patch
      - update
      - watch
