---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: replay-sink
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: replay-sink
  replicas: 1
  template:
    metadata:
      labels:
        app: replay-sink
    spec:
      containers:
      - name: replay-sink
        image: archbungle/load-replay:0.0.12
        imagePullPolicy: IfNotPresent 
        securityContext:
          privileged: true
        env:
        - name: PORT_NUMBER
          value: "80"
        - name: ADMIN_PASSWORD
          value: "Crypt0N0m1c0n##"
        - name: LOCAL_LOGFILE_PATH
          value: "/var/log"
        - name: OUTPUT_DIR_PATH
          value: "/replay"
        ports:
          - name: tcp-80
            containerPort: 80
        volumeMounts:
          - name: replay-data
            mountPath: /replay
      volumes:
        - name: replay-data
          persistentVolumeClaim:
            claimName: replay-claim
      imagePullSecrets:
        - name: ragnarok
---
apiVersion: v1
kind: Service
metadata:
  name: replay-service
  namespace: ragnarok
  labels:
    app: replay-sink
spec:
  type: ClusterIP
  selector:
    app: replay-sink
  ports:
    - name: tcp-80
      port: 80
      targetPort: 80
      protocol: TCP
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: replay-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2
