---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-claim
  namespace: ragnarok
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 50Gi
