apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: pulsar
rules:
  - apiGroups: ["","apps","extensions"]
    resources:
      - pods
      - statefulsets
      - deployments
      - deployments/scale
      - "deployments/scale"
    verbs:
      - patch
      - update
      - get
      - list
      - delete
      - scale
      - restart
      - watch
