apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-client
  namespace: kafka
spec:
  containers:
  - name: zookeeper-client
    image: confluentinc/cp-zookeeper:6.1.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
