apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: ragnarok
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_endpoints_name]
          regex: 'node-exporter'
          action: keep

      - job_name: 'load-metrics'
        static_configs:
          - targets: ['sink-service.ragnarok.svc.cluster.local:80']
            labels:
              group: 'load-sinks'
          - targets: ['consumer-service.ragnarok.svc.cluster.local:80']
            labels:
              group: 'load-consumers'
          - targets: ['producer-service.ragnarok.svc.cluster.local:80']
            labels:
              group: 'load-producers'
          - targets: ['loader-service.ragnarok.svc.cluster.local:80']
            labels:
              group: 'loader-service'
          - targets: ['ragnarok-redis-metrics.redis.svc.cluster.local:9121']
            labels:
              group: 'redis-service'
          - targets: ['ingestor-service.ragnarok.svc.cluster.local:80']
            labels:
              group: 'ingestor-service'
