apiVersion: apps/v1
kind: Deployment
metadata:
  name: fxconsumer
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: fxconsumer
  replicas: 1000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 75%
  template:
    metadata:
      labels:
        app: fxconsumer
    spec:
#      nodeSelector:
#        agentpool: np003
      containers:
      - name: fxconsumer
        image: archbungle/load-fxconsumer:pulsar-0.0.5d42
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 0.3
            memory: 14Gi
            ephemeral-storage: 8Gi 
          limits:
            cpu: 0.5
            memory: 16Gi
            ephemeral-storage: 16Gi
        env:
        - name: FIX_PERFORMANCE_TEST_SERVICE
          value: "fxconsumer"
        - name: FIXTOOL_TEST_MODE
          value: "ord"
        - name: FIXTOOL_CONF_FILE
          value: "/app/fix-perf-tools/config/config.properties"
        - name: FIXTOOL_CREDENTIAL_FILE
          value: "/app/fix-perf-tools/config/users.csv"
        - name: FIXTOOL_JAR_PATH
          value: "/app/fix-perf-tools/target/fix-client-1.0-SNAPSHOT.jar"
        - name: FIXTOOL_INSTRUMENT_PATH
          value: "/app/fix-perf-tools/config/instruments.csv"
        - name: FIX_ORDERS_RATE
          value: "1000"
        - name: FIX_ORDERS_NEW_PERCENTAGE
          value: "50"
        - name: FIX_ORDERS_MATCHING_PERCENTAGE
          value: "0"
        - name: FIX_ORDERS_CANCEL_PERCENTAGE
          value: "50"
        - name: STATS_PRINTING_RATE
          value: "5"
        - name: FIX_OM_TARGET_COMPID
          value: "pt.fix-om.equos"
        - name: FIX_OM_HOST_IP
          value: "10.0.46.99"
        - name: FIX_OM_HOST_PORT
          value: "4802"
        - name: FIX_MD_TARGET_COMPID
          value: "testnet.fix-om.equos"
        - name: FIX_MD_HOST_IP
          value: "10.0.46.99"
        - name: FIX_MD_HOST_PORT
          value: "4802"
        - name: USER1_USERNAME 
          value: "test_eqonex_pt_22may16_indi_0lad@harakirimail.com"
        - name: USER1_PASSWORD
          value: "Diginextest@123"
        - name: USER1_COMPID
          value: "102283"    
        - name: API_BASE_URL
          value: "trading-api.dexp-pt.com"
        - name: TRADING_API_PASSWORD
          value: "Eqonex@123456"
        - name: TRADING_API_USERNAME
          value: "ngocdf1_qa_indi_7uxp@mailinator.com"
        - name: TRADING_API_CLORID
          value: "test-1-traiano45"
        - name: BLOCKWAIT_ACK
          value: "1"
        - name: NUM_JOBS
          value: "1"
        - name: NUM_WORKERS
          value: "1"
        - name: CANCEL_BATCH_LIMIT
          value: "10"
        - name: CANCEL_ALL_THRESHOLD
          value: "100"
        - name: PULSAR_BROKER_SERVICE_ADDRESS
          value: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: PULSAR_CONSUMER_SUBSCRIPTION_NAME
          value: "sub001"
        - name: MESSAGE_TOPIC
          value: "ragnarok/transactions/requests"
        - name: KAFKA_BROKER_SERVICE_ADDRESS
          value: "kafka-cp-kafka.kafka.svc.cluster.local:9092"
        - name: CONSUMER_GROUP
          value: "cg001"
        - name: CONSUMER_COMMIT_INTERVAL
          value: "1"
        - name: LOCAL_LOGFILE_PATH
          value: "/applogs"
        - name: DEADLETTER_TOPIC
          value: "deadLetter"
        - name: METRICS_TOPIC
          value: "metrics"      
        - name: TARGET_API_URL
          value: "http://sink-service.ragnarok.svc.cluster.local/sink-orders"
        - name: PORT_NUMBER
          value: "80"
        - name: REDIS_MASTER_ADDRESS
          value: "ragnarok-redis-master.redis.svc.cluster.local:6379"
        - name: REDIS_ALLOCATOR_NS_INDEX
          value: "11"
        - name: REDIS_REPLICA_ADDRESS
          value: "ragnarok-redis-replicas.redis.svc.cluster.local:6379"
        - name: REDIS_PASS
          value: "Yj7Oe21iHz"
        ports:
          - name: tcp-80
            containerPort: 80
      imagePullSecrets:
        - name: ragnarok
---
kind: Service
apiVersion: v1
metadata:
  name: fxconsumer-service
  namespace: ragnarok
spec:
  type: NodePort
  selector:
    app: fxconsumer
  ports:
    - name: tcp-80
      port: 80
      nodePort: 30079
      protocol: TCP
