---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wsubscriber
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wsubscriber
  replicas: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wsubscriber
    spec:
#      nodeSelector:
#        agentpool: np001
      containers:
      - name: wsubscriber
        image: archbungle/ws-subscriber:0.0.2d1
        imagePullPolicy: IfNotPresent
        env:
        - name: WS_URL
          value: "eqo-sit.com"
        - name: WS_USERNAME
          value: "ngocdf1_qa_indi_7uxp@mailinator.com"
        - name: WS_PASSWORD
          value: "Eqonex@123456"
        - name: USER_ACCOUNT_ID
          value: "2661"
        - name: TOKEN
          value: "l1Q21BJzMZb39hWI"
        - name: SECRET_KEY
          value: "c6Z36Y2mckce7MWsGxi0HZ1n"
        - name: REDIS_MASTER_ADDRESS
          value: "ragnarok-redis-master.redis.svc.cluster.local:6379"
        - name: REDIS_REPLICA_ADDRESS
          value: "ragnarok-redis-replicas.redis.svc.cluster.local:6379"
        - name: REDIS_PASS
          value: "Yj7Oe21iHz"
        - name: ADMIN_PASSWORD
          value: "somethingrandom"
        - name: CONTINUE
          value: "1"
        ports:
          - name: tcp-80
            containerPort: 80
      imagePullSecrets:
        - name: ragnarok
