---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: producer
  namespace: ragnarok
spec:
  selector:
    matchLabels:
      app: producer
  replicas: 100
  podManagementPolicy: "Parallel"
  serviceName: producer-service
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: archbungle/load-tester:pulsar-0.0.56d15
        imagePullPolicy: IfNotPresent
        env:
        - name: NUM_JOBS
          value: "200"
        - name: NUM_WORKERS
          value: "200"
        - name: PULSAR_BROKER_SERVICE_ADDRESS
          value: "pulsar://pulsar-broker.pulsar.svc.cluster.local:6650"
        - name: PULSAR_CONSUMER_SUBSCRIPTION_NAME
          value: "sub002"
        - name: DEBUG_ENABLE
          value: "1"
        - name: MESSAGE_TOPIC
          value: "ragnarok/transactions/requests"
        - name: REDIS_MASTER_ADDRESS
          value: "ragnarok-redis-master.redis.svc.cluster.local:6379"
        - name: REDIS_ALLOCATOR_NS_INDEX
          value: "11"
        - name: REDIS_REPLICA_ADDRESS
          value: "ragnarok-redis-replicas.redis.svc.cluster.local:6379"
        - name: REDIS_PASS
          value: "Yj7Oe21iHz"
        - name: CONSUMER_GROUP
          value: "cg002"
        - name: DATA_SOURCE_DIRECTORY
          value: "/datastore"
        - name: DATA_OUT_DIRECTORY
          value: "/processed"
        - name: LOCAL_LOGFILE_PATH
          value: "/applogs"
        ports:
          - name: tcp-80
            containerPort: 80
      imagePullSecrets:
        - name: ragnarok
---
kind: Service
apiVersion: v1
metadata:
  name: producer-service
  namespace: ragnarok
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - name: tcp-80
      port: 80
      nodePort: 30082
      protocol: TCP
